#!/bin/bash
case "$1" in
*.ml)
	. ~/.opam/opam-init/init.sh
	vim -u <(echo source /usr/share/vim/vimrc; cat $0.vimrc) "$@"
	echo vim -u <(echo source /usr/share/vim/vimrc; cat $0.vimrc) "$@"
;;
*)
	echo nvim -u $0.nvimrc "$@"
	nvim -u `readlink -f $0`.nvimrc "$@"
;;
esac
